[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA-redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# HTML nooit cachen (nieuwe deploys pakken direct door)
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Gehashte assets wél lang cachen
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
